AWSTemplateFormatVersion: 2010-09-09
Description: SSM Parameter demo

Parameters:
  MyKeyName:
    Description: Select the key name from the list.
    Type: AWS::EC2::KeyPair::KeyName
    Default: cfn-key-1
  MyAvailabilityZones:
    Description: Select the AZ/s where you'd like to launch your instance/s. 
    Type: AWS::EC2::AvailabilityZone::Name
    Default: us-east-1a
    AllowedValues:
      - us-east-1a
      - us-east-1b
      - us-east-1c
  MyInstanceType:
    Description: Select the EC2 Instance Type from SSM.


Resources:
  DevEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0742b4e673072066f
      InstanceType: !Ref MyInstanceType
      KeyName: !Ref MyKeyName
      SecurityGroups:
        - default
        - !Ref SSHSecurityGroup
      AvailabilityZone: !Ref MyAvailabilityZones  
      IamInstanceProfile: SSM-FullAccess
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: my new SSH SG
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '8080'
          ToPort: '8080'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '8081'
          ToPort: '8081'
          CidrIp: 0.0.0.0/0        
  DevEC2InstanceEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref DevEC2Instance
      