AWSTemplateFormatVersion: 2010-09-09

Parameters:
  MyKeyName:
    Description: Select the key name from the list.
    Type: AWS::EC2::KeyPair::KeyName
    Default: cfn-key-1

  EnvironmentName:
    Description: Select the environment.
    Type: String
    Default: dev
    AllowedValues: 
      - dev
      - prod

Mappings:
  MyRegionsMap:
    us-east-1:
      AmiID: ami-0742b4e673072066f
    us-west-1:
      AmiID: ami-0577b787189839998

  MyEnvironmentMap:
    dev:
      instanceType: t2.micro
    prod:
      instanceType: t2.small  

Conditions:
  CreateEIPForProd: !Equals [!Ref EnvironmentName, prod]
  CreateDevSecurityGroup: !Equals [!Ref EnvironmentName, dev]

Resources:
  MyVMInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap
        - MyRegionsMap
        - !Ref AWS::Region
        - AmiID
      InstanceType: !FindInMap
        - MyEnvironmentMap
        - !Ref EnvironmentName
        - instanceType
      KeyName: !Ref MyKeyName
      SecurityGroups: !If [CreateDevSecurityGroup, [!Ref DevEnvSecurityGroup]]
  MyProdEIP:
    Type: AWS::EC2::EIP
    Condition: CreateEIPForProd
    Properties:
      InstanceId: !Ref MyVMInstance
  
  DevEnvSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Condition: CreateDevSecurityGroup 
    Properties:
      GroupDescription: Development Environment Security Group
      GroupName: AllowFewPortsForDevEnv
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0


