Resources:
  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/IAMReadOnlyAccess
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 's3:*'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
  S3LambdaToEnableVersioning:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: index.lambda_handler
      Role:
        'Fn::GetAtt':
          - LambdaExecutionRole
          - Arn
      Runtime: python3.8
      Timeout: 180
      Code:
        ZipFile: |
          import json
          import boto3


          class EnableS3Versioning:
              def __init__(self):
                  self._s3 = boto3.client('s3')
                  self.all_buckets = []

              def list_buckets(self):
                  for buckets in self._s3.list_buckets()['Buckets']:
                      s3_buckets = buckets['Name']
                      self.all_buckets.append(s3_buckets)
              
              def enable_bucket_versioning(self):
                  for items in self.all_buckets:
                      versioning = self._s3.put_bucket_versioning(
                          Bucket=items,
                          VersioningConfiguration={
                              'Status': 'Enabled'
                              })
                  listing_them_all = [s3_enabled_version for s3_enabled_version in self.all_buckets]
                  for item in listing_them_all:
                      print(f"We eneabled versioning in bucket: '{item}'.")

          def lambda_handler(event, context):
              s3 = EnableS3Versioning()
              s3.list_buckets()
              s3.enable_bucket_versioning()
  ConfigRuleForS3:
    Type: 'AWS::Config::ConfigRule'
    DependsOn: S3LambdaToEnableVersioning
    Properties:
      ConfigRuleName: s3-bucket-versioning-enabled
      Description: >-
        Checks whether versioning is enabled for your S3 buckets. Optionally,
        the rule checks if MFA delete is enabled for your S3 buckets
      Scope:
        ComplianceResourceTypes:
          - 'AWS::S3::Bucket'
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_VERSIONING_ENABLED

  CreateEventBridgeToTriggerLambda:
    Type: AWS::Events::Rule
    Properties: 
      Description: Enable Version in all S3 Buckets.
      EventBusName: default
      EventPattern: {"source": ["aws.config"]}
      Name: AWS-Config-Auto-Remediation-S3-Versioning
      Targets: 
        - Arn: !GetAtt 
            - S3LambdaToEnableVersioning
            - Arn
          Id: S3LambdaToEnableVersioning

  PermissionForEventsToInvokeLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: !Ref S3LambdaToEnableVersioning
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: 
        Fn::GetAtt: 
          - CreateEventBridgeToTriggerLambda
          - Arn      


  
  S3LambdaEnableAccessLogs:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: index.lambda_handler
      Role:
        'Fn::GetAtt':
          - LambdaExecutionRole
          - Arn
      Runtime: python3.8
      Timeout: 180
      Code:
        ZipFile: |
          import json
          import boto3

          class EnableAccessLogging:
              def __init__(self):
                  self._s3_service_client = boto3.client("s3")
                  self._s3_service_resource = boto3.resource("s3")
                  self._iam_service_client = boto3.client("sts")
                      
              def list_all_buckets(self):
                  """ List all buckets and append them to a list """
                  self._all_buckets = [buckets['Name'] for buckets in self._s3_service_client.list_buckets()['Buckets']]
                  for num, list_buckets in enumerate(self._all_buckets, start= 1):
                      print(f"{num}- {list_buckets}")
              
              def get_account_num(self):
                  """ Get account number """
                  self.account_number = self._iam_service_client.get_caller_identity()['Account']
                  self.access_logs_bucket = f"access-logging-{self.account_number}"
                  
              def put_bucket_prefix(self):
                  for add_prefix in self._all_buckets:
                      if self.access_logs_bucket in add_prefix:
                          for x in self._all_buckets:
                              self._s3_service_client.put_object(
                                  Bucket= self.access_logs_bucket,
                                  Key= f"{self.account_number}/{x}/"
                                  )
              def enable_access_logging(self):
                  """ Enable access loging in all buckets and send them to a target bucket """
                  bucket_acl = self._s3_service_resource.BucketAcl(self.access_logs_bucket)
                  bucket_acl_grants = bucket_acl.grants
                  bucket_acl_grants.append(             
                          {
                              'Grantee': {
                                  'Type': 'Group',
                                  'URI': 'http://acs.amazonaws.com/groups/s3/LogDelivery'
                              },
                              'Permission': 'WRITE'
                          }
                          )
                          
                  bucket_acl_grants.append(                
                          {
                              'Grantee': {
                                  'Type': 'Group',
                                  'URI': 'http://acs.amazonaws.com/groups/s3/LogDelivery'
                              },
                              'Permission': 'READ_ACP'
                          }
                          )
                          
                  canonical_id = bucket_acl.owner['ID']
                  response = bucket_acl.put(
                      AccessControlPolicy={
                      'Grants': bucket_acl_grants,
                      'Owner': {
                          'ID': canonical_id                
                      }})
                      
                  
                  for list_s3_buckets in self._all_buckets:
                      for items in self._all_buckets:
                          response = self._s3_service_client.put_bucket_logging(
                              Bucket = items,
                              BucketLoggingStatus= {
                                  'LoggingEnabled': {
                                      'TargetBucket': self.access_logs_bucket,
                                      'TargetPrefix': f"{self.account_number}/{items}/"
                                  }
                              }
                          )


          def lambda_handler(event, context):
              object_1 = EnableAccessLogging()
              object_1.list_all_buckets()
              object_1.get_account_num()
              object_1.put_bucket_prefix()
              object_1.enable_access_logging()

  ConfigRuleForS3AccessLogs:
    Type: 'AWS::Config::ConfigRule'
    DependsOn: S3LambdaEnableAccessLogs
    Properties:
      ConfigRuleName: s3-bucket-logging-enabled
      Description: >-
        Checks whether access logging is enabled for your S3 buckets.
      Scope:
        ComplianceResourceTypes:
          - 'AWS::S3::Bucket'
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_LOGGING_ENABLED

  CreateEventBridgeToTriggerLambdaForAccessLogging:
    Type: AWS::Events::Rule
    Properties: 
      Description: Enable Access Logging in all S3 Buckets.
      EventBusName: default
      EventPattern: {"source": ["aws.config"]}
      Name: AWS-Config-Auto-Remediation-S3-AccessLogging
      Targets: 
        - Arn: !GetAtt 
            - S3LambdaEnableAccessLogs
            - Arn
          Id: S3LambdaEnableAccessLogs

  PermissionForEventsToInvokeLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: !Ref S3LambdaEnableAccessLogs
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: 
        Fn::GetAtt: 
          - CreateEventBridgeToTriggerLambdaForAccessLogging
          - Arn


  S3LambdaEnableSSE:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: index.lambda_handler
      Role:
        'Fn::GetAtt':
          - LambdaExecutionRole
          - Arn
      Runtime: python3.8
      Timeout: 180
      Code:
        ZipFile: |
          import json
          import boto3

          def lambda_handler(event, context):
              s3_buckets = boto3.client("s3")
              all_buckets = []
              
              for buckets in s3_buckets.list_buckets()['Buckets']:
                  all_buckets.append(buckets['Name'])
                  
              for items in all_buckets:
                  response = s3_buckets.put_bucket_encryption(
              Bucket=items,
                  ServerSideEncryptionConfiguration={
                  'Rules': [
                      {
                          'ApplyServerSideEncryptionByDefault': {
                              'SSEAlgorithm': 'AES256'
                          },
                          'BucketKeyEnabled': False
                      },
                  ]
              },)

  ConfigRuleForS3SSE:
    Type: 'AWS::Config::ConfigRule'
    DependsOn: S3LambdaEnableSSE
    Properties:
      ConfigRuleName: s3-bucket-server-side-encryption-enabled
      Description: >-
        Checks that your Amazon S3 bucket either has Amazon S3 default encryption enabled or that the S3 bucket policy explicitly denies put-
        object requests without server side encryption that uses AES-256 or AWS Key Management Service.
      Scope:
        ComplianceResourceTypes:
          - 'AWS::S3::Bucket'
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_SERVER_SIDE_ENCRYPTION_ENABLED

  CreateEventBridgeToTriggerLambdaForS3SSE:
    Type: AWS::Events::Rule
    Properties: 
      Description: Enable SSE in all S3 Buckets.
      EventBusName: default
      EventPattern: {"source": ["aws.config"]}
      Name: AWS-Config-Auto-Remediation-S3-SSE
      Targets: 
        - Arn: !GetAtt 
            - S3LambdaEnableSSE
            - Arn
          Id: S3LambdaEnableSSE

  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: !Ref S3LambdaEnableSSE
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: 
        Fn::GetAtt: 
          - CreateEventBridgeToTriggerLambdaForS3SSE
          - Arn

